# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-02 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlpModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='nlpModel',
        ),
    ]
